export const CONNECTING = 'CONNECTING';
export const CONNECTED = 'CONNECTED';
export const CONNECT_ERROR= 'CONNECT_ERROR';
export const SENDING_IMG='SENDING_IMG';
export const SEND_DONE='SEND_DONE';
export const SEND_ERROR='SEND_ERROR';
export const RECEIVE='RECEIVE';
export const PROGRESS='PROGRESS';
export const SEND= 'SEND';